version: '3.9'

services:
  api:
    build: .
    container_name: creditfraud-api
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns_db:/app/mlruns_db
      - ./data:/app/data
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlruns_db/mlflow.db
    depends_on:
      - mlflow

  mlflow:
    image: python:3.11-slim
    container_name: mlflow-server
    working_dir: /app
    volumes:
      - ./mlruns_db:/app/mlruns_db
      - ./mlruns:/app/mlruns
    ports:
      - "5001:5001"
    command: >
      mlflow server 
      --backend-store-uri sqlite:///mlruns_db/mlflow.db 
      --default-artifact-root ./mlruns 
      --host 0.0.0.0 
      --port 5001
